
(defun color-theme-ruby-blue ()
  "Ruby Blue color theme, based on the TextMate theme"
  (interactive)
  (let ((color-theme-is-cumulative t))
    (color-theme-dark-blue2)
    (color-theme-install
     '(color-theme-ruby-blue
       ((background-color . "#121E31")
        (background-mode . dark)
        (background-toolbar-color . "#253b76")
        (border-color . "#000")
        (bottom-toolbar-shadow-color . "#000")
        (cursor-color   . "#FFFFFF")
        (foreground-color . "#FFFFFF")
        (top-toolbar-shadow-color . "#111"))
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (button ((t (:bold t))))
       (custom-button-face ((t (:bold t :foreground "#999"))))
       (font-lock-builtin-face ((t (:foreground "#428BDD"))))
       (font-lock-comment-face ((t (:foreground "#428BDD"))))
       (font-lock-comment-delimiter-face ((t (:foreground "#428BDD"))))
       (font-lock-constant-face ((t (:foreground "#8AA6C1"))))
       (font-lock-doc-string-face ((t (:foreground "Yellow"))))
       (font-lock-doc-face ((t (:foreground "Yellow"))))
       (font-lock-function-name-face ((t (:foreground "#FFFFFF"))))
       (font-lock-keyword-face ((t (:foreground "#F8BB00"))))
       (font-lock-preprocessor-face ((t (:foreground "#B6B9F9"))))
       (font-lock-reference-face ((t (:foreground "#777"))))
       (font-lock-string-face ((t (:foreground "#1DC116"))))
       (font-lock-type-face ((t (:foreground "GhostWhite"))))
       (font-lock-variable-name-face ((t (:foreground "#8AA6C1"))))
       (font-lock-warning-face ((t (:bold t :foreground "Magenta"))))
       (fringe ((t (:background "#111" :foreground "#444"))))
       (header-line ((t (:background "#333" :foreground "#000"))))
       (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
       (holiday-face ((t (:background "#000" :foreground "#777"))))
       (isearch ((t (:foreground "pink" :background "red"))))
       (isearch-lazy-highlight-face ((t (:foreground "red"))))
       (italic ((t (:italic t :slant italic))))
       (menu ((t (:background "#253b76" :foreground "white"))))
       (minibuffer-prompt ((t (:foreground "555"))))
       (modeline ((t (:background "#253b76" :foreground "yellow"))))
       (mode-line-inactive ((t (:background "#253b76" :foreground "darkgray"))))
       (modeline-buffer-id ((t (:background "#253b76" :foreground "white"))))
       (modeline-mousable-minor-mode ((t (:background "#000" :foreground "#555"))))
       (pointer ((t (:foreground "IndianRed"))))
       (region ((t (:foreground "GhostWhite" :background "#253b76"))))
       (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
       (show-paren-match-face ((t (:foreground "white" :background "light slate blue"))))
       (show-paren-mismatch-face ((t (:foreground "white" :background "red"))))
       (tool-bar ((t (:background "#253b76" :foreground "white"))))
       (tooltip ((t (:background "#333" :foreground "#777"))))
       (underline ((t (:bold t))))
       (variable-pitch ((t (nil))))
       (widget-button-face ((t (:bold t :foreground "#888"))))
       (widget-field-face ((t (:bold t :foreground "#999"))))))))
